title: MedCom Messaging
logo: ../Medcom_logo_2015.png
description: MedCom Messaging is your site for MedComs Messaging standards and profiles.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
